export const TOP_RATED_RICEPES = [
  {
    id: 1,
    title: 'The Best Soft Chocolate Chip Cookies',
    image: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e',
    reviews: 1864,
    rating: 4.5,
  },
  {
    id: 2,
    title: 'The Best Sunday Chili',
    image: 'https://images.unsplash.com/photo-1546549032-9571cd6b27df',
    reviews: 115,
    rating: 4.9,
  },
  {
    id: 3,
    title: 'Miracle No Knead Bread',
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df',
    reviews: 578,
    rating: 4.8,
  },
  {
    id: 4,
    title: 'Best Anytime Baked Chicken Meatballs',
    image: 'https://images.unsplash.com/photo-1529042410759-befb1204b468',
    reviews: 736,
    rating: 4.9,
  },
  {
    id: 5,
    title: 'The Best Chicken Tinga Tacos',
    image: 'https://images.unsplash.com/photo-1552332386-f8dd00dc2f85',
    reviews: 185,
    rating: 4.9,
  },
  {
    id: 6,
    title: 'The Best Detox Crockpot Lentil Soup',
    image: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a',
    reviews: 373,
    rating: 4.8,
  },
  {
    id: 7,
    title: 'Vegetarian Shepherd\'s Pie',
    image: 'https://plus.unsplash.com/premium_photo-1726718442760-cccbd5f1e252?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    reviews: 397,
    rating: 4.8,
  },
  {
    id: 8,
    title: 'Fruit Pizza',
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187',
    reviews: 67,
    rating: 4.8,
  },
  {
    id: 9,
    title: 'Fluffiest Blueberry Pancakes',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93',
    reviews: 356,
    rating: 4.8,
  },
];

export const CATEGORIES = {
  popular: ['Quick and Easy', 'Instant Pot', 'Meal Prep', 'Vegan', 'Vegetarian', 'Sugar-Free', 'Pasta', 'Tacos', 'Bowls', 'Soups', 'Salads', 'Dinner', 'Kid-Friendly', 'Most Popular', 'All Recipes'],
  mealType: ['Breakfast', 'Lunch', 'Dinner', 'Appetizer', 'Snacks', 'Desserts', 'Drinks'],
  course: ['Appetizer', 'Soups', 'Salads', 'Sauces', 'Sides', 'Desserts', 'Snacks', 'Baking', 'Sandwiches', 'Main Dishes'],
  diet: ['Dairy-Free', 'Gluten-Free', 'Kid-Friendly', 'Healthy', 'Sugar-Free', 'Vegan', 'Vegetarian'],
  season: ['Spring', 'Summer', 'Fall', 'Winter'],
  method: ['Casserole', 'Instant Pot', 'Slow Cooker', 'Sheet Pan', 'Stovetop'],
  ingredient: ['5 Ingredients', 'Avocado', 'Bacon', 'Bell Pepper', 'Berry', 'Broccoli', 'Carrot', 'Cauliflower', 'Chocolate', 'Eggs', 'Fish and Seafood', 'Jalapeño', 'Kale', 'Legume', 'Lemon', 'Lime', 'Meat and Chicken', 'Mushroom', 'Pasta', 'Peanut Butter', 'Pumpkin', 'Quinoa', 'Rice', 'Salmon', 'Spinach', 'Sweet Potato', 'Tofu', 'Tomato', 'Zucchini'],
  series: ['Feeding a Broken Heart', 'Holiday Series', 'Plant-Powered January', 'SOS Series', 'The Soup Series', 'Sugar Free January'],
};
